from prometheus_client import Counter, Gauge, Histogram

strategy_runs_total = Counter("strategy_runs_total", "Total number of strategy orchestration runs", ["side", "status"])
strategy_stop_loss_total = Counter("strategy_stop_loss_total", "Total number of stop-loss triggers", ["symbol", "side"])
strategy_take_profit_total = Counter("strategy_take_profit_total", "Total number of take-profit executions", ["symbol", "side", "level"])
strategy_stage_trigger_total = Counter("strategy_stage_trigger_total", "Total number of stage triggers", ["symbol", "side", "stage_no"])
strategy_stage_order_fail_total = Counter("strategy_stage_order_fail_total", "Total number of stage order failures", ["symbol", "side", "stage_no", "reason_code"])
user_stream_events_total = Counter("user_stream_events_total", "Total number of Binance user stream events", ["event_type"])
user_stream_reconnect_total = Counter("user_stream_reconnect_total", "Total number of Binance user stream reconnects")
listen_key_keepalive_total = Counter("listen_key_keepalive_total", "Total listen key keepalive attempts", ["status"])
position_reconcile_total = Counter("position_reconcile_total", "Total position reconcile runs", ["status"])
position_qty_mismatch_total = Counter("position_qty_mismatch_total", "Total local/exchange quantity mismatches", ["symbol", "side"])
kill_switch_trigger_total = Counter("kill_switch_trigger_total", "Total account kill-switch triggers", ["exchange_account_id", "reason_code"])
kill_switch_enabled = Gauge("kill_switch_enabled", "Whether kill-switch is enabled for an account", ["exchange_account_id"])
strategy_active_positions = Gauge("strategy_active_positions", "Active strategy positions", ["symbol", "side"])
user_stream_connected = Gauge("user_stream_connected", "Whether user stream connection is alive")
scheduler_leader_status = Gauge("scheduler_leader_status", "Whether current node is leader")
binance_algo_order_total = Counter("binance_algo_order_total", "Total Algo order submissions", ["order_type", "status"])
binance_api_requests_total = Counter("binance_api_requests_total", "Total Binance API requests", ["endpoint", "method", "status"])
binance_api_request_latency_seconds = Histogram("binance_api_request_latency_seconds", "Binance API latency", ["endpoint", "method"])
